FROM node:20-alpine.22

WORKDIR /app

RUN apk update && apk upgrade --no-cache

COPY package*.json ./
RUN npm install --ignore-workspace

RUN chown -R node:node /usr/src/app
USER node

COPY src/ ./src/

EXPOSE 3000

CMD ["npm", "run", "dev"]