// lib/mockData.ts
// Shared mock data used by all API routes

export const MOCK_LISTINGS = [
    {
        id: '1',
        title: 'Database Systems: Concepts',
        author: 'Abraham Silberschatz, Henry Korth, S Sudarshan',
        edition: '7th',
        isbn: '978-0-07-352332-3',
        moduleCode: 'COS326',
        faculty: 'EBIT',
        condition: 'GOOD',
        annotationLevel: 'LIGHT',
        price: 350,
        description: 'Well maintained textbook, only used for Semester 2. A few light pencil marks in chapter 3 and 4, otherwise clean.',
        images: [],
        status: 'APPROVED',
        createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
        seller: {
            id: 's1',
            name: 'Hugh Campbell',
            email: 'hugh@tuks.co.za',
            verified: true,
            rating: 4.8,
            reviewCount: 32,
            memberSince: '2026',
            meetupPreference: 'Hatfield campus, UP — Wednesdays after 4pm',
        },
    },
    {
        id: '2',
        title: 'Compiler Construction',
        author: 'Alfred V. Aho, Monica S. Lam',
        edition: '2nd',
        isbn: '978-0-13-468599-1',
        moduleCode: 'COS301',
        faculty: 'EBIT',
        condition: 'LIKE_NEW',
        annotationLevel: 'NONE',
        price: 400,
        description: 'Bought for COS301 but switched modules. Never used, still has the shrink wrap crease on cover.',
        images: [],
        status: 'APPROVED',
        createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
        seller: {
            id: 's2',
            name: 'Priya Naidoo',
            email: 'priya@tuks.co.za',
            verified: true,
            rating: 5.0,
            reviewCount: 7,
            memberSince: '2025',
            meetupPreference: 'Engineering building, Tuesdays 10am–12pm',
        },
    },
    {
        id: '3',
        title: 'Calculus: Principles and Practice',
        author: 'James Stewart',
        edition: '8th',
        isbn: '978-1-285-74062-1',
        moduleCode: 'WTW158',
        faculty: 'NAT',
        condition: 'GOOD',
        annotationLevel: 'NONE',
        price: 300,
        description: 'Good condition. Used for first year calculus. Spine is slightly worn but all pages intact.',
        images: [],
        status: 'APPROVED',
        createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
        seller: {
            id: 's3',
            name: 'Liam van der Berg',
            email: 'liam@tuks.co.za',
            verified: false,
            rating: 4.2,
            reviewCount: 4,
            memberSince: '2026',
            meetupPreference: 'Groenkloof campus, flexible times',
        },
    },
    {
        id: '4',
        title: 'Quantity Surveying Practice',
        author: 'Ivor Seeley',
        edition: '4th',
        isbn: '978-0-33-364612-0',
        moduleCode: 'BOC201',
        faculty: 'ENG',
        condition: 'ACCEPTABLE',
        annotationLevel: 'HEAVY',
        price: 250,
        description: 'Heavily annotated but all annotations are helpful study notes. Great if you want a pre-studied copy.',
        images: [],
        status: 'APPROVED',
        createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
        seller: {
            id: 's4',
            name: 'Amara Dlamini',
            email: 'amara@tuks.co.za',
            verified: true,
            rating: 4.5,
            reviewCount: 12,
            memberSince: '2024',
            meetupPreference: 'Hatfield campus, anytime after 2pm',
        },
    },
    {
        id: '5',
        title: 'Introduction to Sociology',
        author: 'Anthony Giddens',
        edition: '8th',
        isbn: '978-1-509-53235-7',
        moduleCode: 'SOC101',
        faculty: 'HUM',
        condition: 'GOOD',
        annotationLevel: 'LIGHT',
        price: 280,
        description: 'Used for one semester. Some highlighting in chapters 1–3. Good overall condition.',
        images: [],
        status: 'APPROVED',
        createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
        seller: {
            id: 's5',
            name: 'Sophie Kruger',
            email: 'sophie@tuks.co.za',
            verified: false,
            rating: 4.0,
            reviewCount: 2,
            memberSince: '2026',
            meetupPreference: 'Humanities building, Mondays or Thursdays',
        },
    },
    {
        id: '6',
        title: "Shakespearean Views",
        author: 'Harold Bloom',
        edition: '3rd',
        isbn: '978-1-594-48293-8',
        moduleCode: 'ENG201',
        faculty: 'HUM',
        condition: 'GOOD',
        annotationLevel: 'NONE',
        price: 200,
        description: 'Clean copy, no markings. Purchased for ENG201 but the module switched to a different text.',
        images: [],
        status: 'APPROVED',
        createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
        seller: {
            id: 's6',
            name: 'Ethan Pretorius',
            email: 'ethan@tuks.co.za',
            verified: true,
            rating: 4.6,
            reviewCount: 9,
            memberSince: '2025',
            meetupPreference: 'Library café, weekday mornings',
        },
    },
    // PENDING listings (for admin dashboard + mine page)
    {
        id: '7',
        title: 'Law of Contract in South Africa',
        author: 'Dale Hutchison',
        edition: '7th',
        isbn: '978-0-19-904413-7',
        moduleCode: 'PVR210',
        faculty: 'LAW',
        condition: 'LIKE_NEW',
        annotationLevel: 'NONE',
        price: 450,
        description: 'Bought new this semester, decided to go digital. Still in perfect condition.',
        images: [],
        status: 'PENDING',
        createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
        seller: {
            id: 's7',
            name: 'Naledi Mokoena',
            email: 'naledi@tuks.co.za',
            verified: true,
            rating: 4.9,
            reviewCount: 3,
            memberSince: '2025',
            meetupPreference: 'Law building, anytime',
        },
    },
    {
        id: '8',
        title: 'Financial Accounting',
        author: 'Robert Libby',
        edition: '9th',
        isbn: '978-1-259-72210-9',
        moduleCode: 'FBS201',
        faculty: 'ECO',
        condition: 'GOOD',
        annotationLevel: 'LIGHT',
        price: 380,
        description: 'Light notes in margin for first 5 chapters. Used for one year.',
        images: [],
        status: 'PENDING',
        createdAt: new Date(Date.now() - 6 * 3600000).toISOString(),
        seller: {
            id: 's8',
            name: 'Kagiso Sithole',
            email: 'kagiso@tuks.co.za',
            verified: false,
            rating: 0,
            reviewCount: 0,
            memberSince: '2026',
            meetupPreference: 'EMS building, flexible',
        },
    },
]

// Listings that belong to the current logged-in user (mock)
export const MY_MOCK_LISTINGS = [
    MOCK_LISTINGS[0], // approved
    MOCK_LISTINGS[1], // approved
    MOCK_LISTINGS[6], // pending
]